#!/usr/bin/env php
<?php

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

namespace Differ\Differ\genDiff;

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>
Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish | plain | json]
DOC;

$args = Docopt::handle($doc, array('version'=>'version 1.0'));

/*foreach ($args as $k=>$v) {
    echo $k.': '.json_encode($v).PHP_EOL;
}
*/

if ($args["<firstFile>"] && $args["<secondFile>"]) {
	$result = genDiff((string)$args["<firstFile>"], (string)$args["<secondFile>"], $args["--format"]);
	print_r($result);
}
